# Generated by Django 5.2.7 on 2025-11-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoutfitShowroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
