# Generated by Django 5.2.6 on 2025-11-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoutfitShowroom', '0002_style_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='outfits/'),
        ),
    ]
