# Generated by Django 5.2.6 on 2025-11-05 14:27
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoutfitShowroom', '0003_outfit_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='genero',
            field=models.CharField(choices=[('mujer', 'Mujer'), ('hombre', 'Hombre'), ('ambiguo', 'Ambiguo')], default='ambiguo', max_length=10),
        ),
    ]
