# Generated by Django 5.2.6 on 2025-11-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoutfitShowroom', '0004_outfit_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutfitIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('descripcion', models.TextField()),
                ('ocasion', models.CharField(choices=[('Casual', 'Casual'), ('Formal', 'Formal'), ('Playa', 'Día de playa'), ('Trabajo', 'Trabajo'), ('Noche', 'De noche')], max_length=20)),
                ('estilos', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='outfit_ideas/')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
