# Generated by Django 5.2.6 on 2025-11-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoutfitShowroom', '0005_outfitidea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outfitidea',
            name='estilos',
        ),
        migrations.AddField(
            model_name='outfitidea',
            name='estilos',
            field=models.ManyToManyField(blank=True, to='appoutfitShowroom.style'),
        ),
    ]
